const UI_TEXT = {
  fr: {
    catalogEyebrow: "Entraînement mathématique",
    catalogTitle: "S'entraîner en mathématiques",
    catalogLead: "Des séries courtes et ciblées pour consolider les automatismes utiles en L1 et L2.",
    categories: "Catégories",
    tools: "Entraînements",
    openCategory: "Voir les entraînements",
    openTool: "Commencer",
    backCatalog: "Toutes les catégories",
    backCategory: "Retour à la catégorie",
    backToTool: "Retour à",
    unavailable: "Cet entraînement n'existe pas ou n'est pas encore disponible.",
    exerciseChoice: "Exercice à travailler",
    level: "Niveau",
    questions: "Nombre de questions",
    noLevel: "Aucun choix de niveau n'est nécessaire.",
    start: "Démarrer la série",
    validate: "Valider",
    next: "Question suivante",
    restart: "Recommencer",
    seriesComplete: "Série terminée",
    score: "Score actuel",
    statistics: "Statistiques",
    correct: "Bonnes réponses",
    correctOnTime: "Bonnes réponses dans les temps",
    errors: "Erreurs",
    outOfTime: "Hors délai",
    successRate: "Réussite",
    streak: "Série actuelle",
    bestStreak: "Meilleure série de réponses correctes",
    averageTime: "Temps moyen",
    question: "Question",
    correction: "Correction",
    explanation: "Explication",
    insight: "À retenir",
    hint: "Indice",
    nextHint: "Indice suivant",
    courseReminder: "Rappel de cours",
    viewCourseReminders: "Voir les rappels de cours",
    allCourseReminders: "Tous les rappels de cours",
    courseOverviewLead: "Relisez les règles utiles avant de démarrer. Vous pourrez retrouver chaque rappel pendant la série.",
    close: "Fermer",
    true: "Vrai",
    false: "Faux",
    answer: "Votre réponse",
    answerPlaceholder: "Saisir une réponse",
    solutionSetPlaceholder: "Ex. -2 ; 3/4",
    timeRemaining: "Temps restant",
    timeExpired: "Temps écoulé",
    timeExpiredShort: "Terminé !",
    timeExpiredCanAnswer: "Vous pouvez encore répondre.",
    timeExpiredNoAnswer: "Aucune réponse dans le temps imparti.",
    correctButLate: "Bonne réponse, mais hors délai.",
    incorrectAndLate: "Réponse incorrecte et hors délai.",
    seconds: "s",
    timed: "Chronométré",
    questionBank: "Banque de questions",
    generated: "Questions générées",
    studyMode: "Exercice corrigé",
    showSolution: "Voir la correction",
    hideSolution: "Masquer la correction",
    anotherExercise: "Un autre exercice",
    progress: "Progression",
    keyboardHint: "Entrée pour valider puis passer à la suite.",
    feedbackCorrectTitle: "Excellent !",
    feedbackCorrectLead: "Le résultat est juste. Continuez sur cette lancée !",
    feedbackIncorrectTitle: "Dommage !",
    feedbackIncorrectLead: "La prochaine sera la bonne.",
    feedbackEquivalentTitle: "Presque !",
    feedbackEquivalentLead: "Le calcul est juste, mais la forme demandée reste à ajuster.",
    feedbackTimeoutTitle: "Temps écoulé",
    feedbackTimeoutLead: "Cette question est comptée hors délai, pas comme une erreur de calcul.",
    feedbackLateTitle: "Juste, mais hors délai",
    feedbackLateLead: "La réponse est correcte. Essayez maintenant de gagner en rapidité.",
    feedbackPlaceholder: "Le résultat et la correction s’afficheront ici après votre réponse.",
    summaryLead: "Voici le bilan détaillé de votre série.",
    responseTimes: "Temps par question",
    responseTimesLead: "Comparez votre rythme d’une question à l’autre.",
    reviewMistakes: "Questions à revoir",
    reviewMistakesLead: "Retrouvez les questions incorrectes et leur réponse attendue.",
    noMistakes: "Aucune erreur à revoir : série parfaite !",
    yourAnswer: "Votre réponse",
    noAnswer: "Aucune réponse",
    expectedAnswer: "Réponse attendue",
    matrixRow: "ligne",
    matrixColumn: "colonne",
  },
  en: {
    catalogEyebrow: "Mathematics practice",
    catalogTitle: "Practise mathematics",
    catalogLead: "Short, focused sessions to strengthen the skills needed in first- and second-year university mathematics.",
    categories: "Categories",
    tools: "Practice tools",
    openCategory: "View practice tools",
    openTool: "Start",
    backCatalog: "All categories",
    backCategory: "Back to category",
    backToTool: "Back to",
    unavailable: "This practice tool does not exist or is not available yet.",
    exerciseChoice: "Exercise to practise",
    level: "Level",
    questions: "Number of questions",
    noLevel: "No level selection is needed.",
    start: "Start session",
    validate: "Check",
    next: "Next question",
    restart: "Start again",
    seriesComplete: "Session complete",
    score: "Current score",
    statistics: "Statistics",
    correct: "Correct answers",
    correctOnTime: "Correct and on time",
    errors: "Errors",
    outOfTime: "Out of time",
    successRate: "Success rate",
    streak: "Current streak",
    bestStreak: "Best streak",
    averageTime: "Average time",
    question: "Question",
    correction: "Correction",
    explanation: "Explanation",
    insight: "Key idea",
    hint: "Hint",
    nextHint: "Next hint",
    courseReminder: "Course reminder",
    viewCourseReminders: "Review course reminders",
    allCourseReminders: "All course reminders",
    courseOverviewLead: "Review the useful rules before starting. Each reminder remains available during the session.",
    close: "Close",
    true: "True",
    false: "False",
    answer: "Your answer",
    answerPlaceholder: "Enter an answer",
    solutionSetPlaceholder: "E.g. -2 ; 3/4",
    timeRemaining: "Time left",
    timeExpired: "Time elapsed",
    timeExpiredShort: "Finished!",
    timeExpiredCanAnswer: "Time is up — you can still answer.",
    timeExpiredNoAnswer: "No answer was submitted within the time limit.",
    correctButLate: "Correct answer, but outside the time limit.",
    incorrectAndLate: "Incorrect answer and outside the time limit.",
    seconds: "s",
    timed: "Timed",
    questionBank: "Question bank",
    generated: "Generated questions",
    studyMode: "Worked exercise",
    showSolution: "Show solution",
    hideSolution: "Hide solution",
    anotherExercise: "Another exercise",
    progress: "Progress",
    keyboardHint: "Press Enter to check and move on.",
    feedbackCorrectTitle: "Excellent!",
    feedbackCorrectLead: "That is correct. Keep going.",
    feedbackIncorrectTitle: "Try again!",
    feedbackIncorrectLead: "Review the solution: the next one is yours.",
    feedbackEquivalentTitle: "Almost!",
    feedbackEquivalentLead: "The mathematics is correct, but the requested form still needs adjusting.",
    feedbackTimeoutTitle: "Time's up",
    feedbackTimeoutLead: "This question is counted as out of time, not as a calculation error.",
    feedbackLateTitle: "Correct, but out of time",
    feedbackLateLead: "Your answer is correct; now try to gain speed.",
    feedbackPlaceholder: "Your result and the solution will appear here after you answer.",
    summaryLead: "Here is the detailed summary of your session.",
    responseTimes: "Time per question",
    responseTimesLead: "Compare your pace from one question to the next.",
    reviewMistakes: "Questions to review",
    reviewMistakesLead: "Review incorrect questions and their expected answers.",
    noMistakes: "No mistakes to review — a perfect session!",
    yourAnswer: "Your answer",
    noAnswer: "No answer",
    expectedAnswer: "Expected answer",
    matrixRow: "row",
    matrixColumn: "column",
  },
};

export function getExerciseUiText(lang) {
  return UI_TEXT[lang] ?? UI_TEXT.fr;
}

export default UI_TEXT;
